export default [
	"The great masses of the people... will more easily fall victims to a big lie than to a small one.",
	"The most foolish mistake we could possibly make would be to permit the conquered Eastern peoples to have arms. History teaches that all conquerors who have allowed their subject races to carry arms have prepared their own downfall by doing so.",
	"It is not truth that matters, but victory.",
	"...obstacles do not exist to be surrendered to, but only to be broken.",
	"What luck for rulers that men do not think.",
	"The leader of genius must have the ability to make different opponents appear as if they belonged to one category.",
	"Who says I am not under the special protection of God?",
	"Go ahead, kill without mercy. After all, who remembers today the Armenian Genocide",
	"A people that fails to preserve the purity of its racial blood thereby destroys the unity of the soul of the national in all its manifestations. A disintegrated national character is the inevitable consequence of a process of disintegration in the blood.",
	"I am a socialist. I see no class and no social estate before me, but that community of the people, made up of people who are liked by blood, united by a language, and subject to a same general fate.",
	"National Socialism is what Marxism might have been if it could have broken its absurd and artificial ties with the democratic order.",
	"The common good before the individual good.",
	"The nationalization of the masses can be successfully achieved only if, in the positive struggle to win the soul of the people, those who spread the international poison among them are exterminated.",
	"This means that a people cannot be made 'national' according to the signification attached to that word by our bourgeois class today - that is to say, nationalism with many reservations- but national in the vehement and extreme sense.",
	"We are not primarily attacking the Jews.",
	"If you win, you need not have to explain...If you lose, you should not be there to explain!",
	"Do not compare yourself to others. If you do so, you are insulting yourself.",
	"if you want to shine like sun first you have to burn like it.",
	"And I can fight only for something that I love, love only what I respect, and respect only what I at least know.",
	"Anyone can deal with victory. Only the mighty can bear defeat.",
	"Think Thousand times before taking a decision But - After taking decision never turn back even if you get Thousand difficulties!!",
	"When diplomacy ends, War begins.",
	"The man who has no sense of history, is like a man who has no ears or eyes",
	"Reading is not an end to itself, but a means to an end.",
	"I use emotion for the many and reserve reason for the few.",
	"He alone, who owns the youth, gains the future.",
	"Words build bridges into unexplored regions.",
	"To conquer a nation, first disarm its citizens.",
	"The victor will never be asked if he told the truth. ",
	"The art of reading and studying consists in remembering the essentials and forgetting what is not essential.",
	"If freedom is short of weapons, we must compensate with willpower.",
	"The only preventative measure one can take is to live irregularly.",
	"The state must declare the child to be the most precious treasure of the people. As long as the government is perceived as working for the benefit of the children, the people will happily endure almost any curtailment of liberty and almost any deprivation.",
	"The very first essential for success is a perpetually constant and regular employment of violence.",
	"As in everything, nature is the best instructor.",
	"Kill, Destroy, Sack, Tell lie; how much you want after victory nobody asks why?",
	"He who would live must fight. He who doesn't wish to fight in this world, where permanent struggle is the law of life, has not the right to exist.",
	"The great strength of the totalitarian state is that it forces those who fear it to imitate it.",
	"Humanitarianism is the expression of stupidity and cowardice.",
	"Obstacles do not exist to be surrendered to, but only to be broken.",
	"The Strong Man is Mightiest Alone.",
	"I respected my father, but I loved my mother",
	"All great movements are popular movements. They are the volcanic eruptions of human passions and emotions, stirred into activity by the ruthless Goddess of Distress or by the torch of the spoken word cast into the midst of the people.",
	"The amount of money that is in your bank at the time of your death is the extra work you did which wasn't necessary",
	"don't let what other people think, stop you from doing the things you love",
	"Conscience is a Jewish invention.",
	"God's and beasts, that is what our world is made of.",
	"Secular schools can never be tolerated because such a school has no religious instruction and a general moral instruction without a religious foundation is built on air; consequently, all character training and religion must be derived from faith...",
	"There is a better chance of seeing a camel pass through the eye of a needle than of seeing a really great man 'discovered' through an election.",
	"It is the press, above all, which wages a positively fanatical and slanderous struggle, tearing down everything which can be regarded as a support of national independence, cultural elevation, and the economic independence of the nation.",
	"Basically National Socialism and Marxism are the same thing",
	"Winning without problem is just victory, but winning with lots of trouble create History ..",
	"Whenever human activity is directed exclusively to the service of the instinct for self-preservation it is called theft or usury, robbery or burglary etc",
	"What good fortune for those in power that people do not think.",
	"I drank my bottle of milk and ate my morsel of bread somewhere on the outskirts, while I circumspectly studied my environment or else fell to meditating on my own harsh lot",
	"The doom of a nation can be averted only by a storm of flowing passion, but only those who are passionate themselves can arouse passion in others.",
	"A sound and energetic mind is only found in a sound and energetic body.",
	"I dream of a state of affairs in which every man would know that he lives and dies for the preservation of the species.",
	"The Goddess of Fate clutched me in her hands and often threatened to smash me; but the will grew stronger as the obstacles increased, and finally the will triumphed."
];
